#!/bin/bash
# messaging_app/kubctl-0x01

# Scale deployment to 3 replicas
kubectl scale deployment django-messaging-app --replicas=3

# Wait a moment for pods to start
sleep 10

# Verify pods are running
kubectl get pods -l app=django-messaging-app

# Perform basic load test using wrk (install wrk if missing)
wrk -t2 -c10 -d10s http://$(minikube service django-messaging-service --url)

# Monitor resource usage
kubectl top pods
