# Generated by Django 5.2.4 on 2025-07-26 14:16

import chats.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', chats.models.CustomUserManager()),
            ],
        ),
    ]
