# Generated by Django 5.2.4 on 2025-07-27 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
